language: objective-c
xcode_project: linphone.xcodeproj
xcode_scheme: linphone
xcode_sdk: iphonesimulator8.1

git:
  submodules: false

branches:
  only:
    - master

env:
    global:
        - VERSION="8.1"
        - BYPASS_TOOLCHECK=1
        - KIF_SCREENSHOTS=Screens
        - secure: "Vvk5rN/mFA22eWSGxpZsQDSnSQY2QFBJphvc66n/bMX9fcm7NHhTDBD5ZfJN4S5FVYN9AIQj0w56gnx8nflJ7dfvhWZ0bjkW2ZPkw1909FLS8fsA2bNwjLU9vI7PAN3Lctxamn3mEcLrg3kzx4OJRQ9Y/PhuaeknP8w2RS/L1Ao="

install: 
    - cd submodules/build 
    - make download-sdk
    - cd ../..
    - git submodule update --init Classes/KIF
    - git submodule update --init --recursive submodules/linphone
    - mkdir -p Screens
    - export KIF_SCREENSHOTS=`pwd`/Screens

after_script:
    - ./Tools/imgur_upload.sh 
